version: '3.8'

services:
  jenkins:
    build: .
    container_name: jenkins
    privileged: true
    user: root
    volumes:
      - .\jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker:ro
    ports:
      - "9080:8080"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: "4GB"
  agent:
    image: dockeragent
    privileged: true
    user: root
    container_name: agent
    networks:
      - backend
    expose:
      - 22
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDQy+abZWh1ZLU370of/0/n8KkptPDbty7wbyAKlj6mmPQ6Nbv4CiTyi7mMLlaOIFqR4g4py8+uNbSGjyBY4Heu8tSU9CjjRGFWsAI2FwuiVdZJ188pii/ZoCkXD3IlPdqFxDPb+Z9PiXi/dtOjf1xfwSCswpGXDwptvp9DXk9RPYifJzCZ9eLmI5qQTRKoKmzKBmvCT6weQyLCzqtUsqBVXRZbZABS14VjxIKmlBye89G3EOJh1eE3C40najBPD5eIm7ZY4e8oUdQ/dPT+4noId6po5+kcLFr3KRRiwNkwADaMa1JJ6RtGXv9+ck5z0+1p4GRJSejHWhtdV3m7724A0sfdfTBpTwVsPiTN0kqNQ4mvUWEPIWWhp3UD6Y9aHQ0d4USmKTUIztRNOk7YgdkBaX7hGNQO+uZCo6CuUcT1FBhNBIyFs+/J4GcTX14NFF3jx9fuF75AfQrNMviB3x0QIizD4Av9z+Vn0rt/+bSDSDT9X1ZlZsF1S/wjI3CGkbc= pedro@DESKTOP-VCT9AKT
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
    deploy:
      resources:
        limits:
          cpus: "6.0"
          memory: "6GB"
  agentNet:
    image: dockernetagent
    privileged: true
    user: root
    container_name: agentNet
    networks:
      - backend
    expose:
      - 22
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDQy+abZWh1ZLU370of/0/n8KkptPDbty7wbyAKlj6mmPQ6Nbv4CiTyi7mMLlaOIFqR4g4py8+uNbSGjyBY4Heu8tSU9CjjRGFWsAI2FwuiVdZJ188pii/ZoCkXD3IlPdqFxDPb+Z9PiXi/dtOjf1xfwSCswpGXDwptvp9DXk9RPYifJzCZ9eLmI5qQTRKoKmzKBmvCT6weQyLCzqtUsqBVXRZbZABS14VjxIKmlBye89G3EOJh1eE3C40najBPD5eIm7ZY4e8oUdQ/dPT+4noId6po5+kcLFr3KRRiwNkwADaMa1JJ6RtGXv9+ck5z0+1p4GRJSejHWhtdV3m7724A0sfdfTBpTwVsPiTN0kqNQ4mvUWEPIWWhp3UD6Y9aHQ0d4USmKTUIztRNOk7YgdkBaX7hGNQO+uZCo6CuUcT1FBhNBIyFs+/J4GcTX14NFF3jx9fuF75AfQrNMviB3x0QIizD4Av9z+Vn0rt/+bSDSDT9X1ZlZsF1S/wjI3CGkbc= pedro@DESKTOP-VCT9AKT
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      resources:
        limits:
          cpus: "6.0"
          memory: "6GB"
  sonarqube:
    image: sonarqube:25.1.0.102122-community
    depends_on:
      - db
    ports:
      - "9000:9000"
    networks:
      - backend
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonarqube
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "1GB"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp
    restart: on-failure
    container_name: sonarqube
  db:
    image: postgres:12-bullseye
    networks:
      - backend
    environment:
      POSTGRES_DB: "sonarqube"
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "256MB"
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    restart: on-failure
    container_name: postgresql

networks:
  backend:
    name: network_jenkins
  host:
    external: true  

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_temp:
  postgresql:
  postgresql_data: