version: '3.8'
services:
  tiendaonline:
    image: app_net
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
    networks:
      - selenoid

networks:
  selenoid:
    name: network_jenkins
    external: true
